"""Dataset statistics for the page charts, computed from the released annotations.

    cd object_vqa && python /path/to/ProcObject-10K-Page/tools/make_stats.py /path/to/ProcObject-10K-Page
"""
import collections
import json
import os
import sys

PAGE = sys.argv[1]
DATA = 'ProcObject-10K-release/data/'
TYPES = ['Precondition Grounding', 'Object State Evolution', 'Counterfactual Reasoning',
         'Mistake Recognition', 'Readiness Assessment']


def main():
    train = json.load(open(DATA + 'training.json'))
    test = json.load(open(DATA + 'testing.json'))
    qa = train + test

    dom = collections.defaultdict(lambda: dict(qa=0, videos=set(), tasks=set()))
    for r in qa:
        d = dom[r['domain']]
        d['qa'] += 1
        d['videos'].add(r['video_path'])
        d['tasks'].add(r['task'])
    domains = sorted(([k, len(v['videos']), v['qa'], len(v['tasks'])] for k, v in dom.items()),
                     key=lambda x: -x[1])

    reasoning = []
    for t in TYPES:
        c = collections.Counter(r['reasoning'] for r in qa if r['qa_type'] == t)
        reasoning.append([t, c['Multi-hop Reasoning'], c['Needle-in-a-Haystack']])

    src_qa = collections.Counter(r['source'] for r in qa)
    src_vid = collections.defaultdict(set)
    for r in qa:
        src_vid[r['source']].add(r['video_path'])
    sources = sorted(([s, len(src_vid[s]), src_qa[s]] for s in src_qa), key=lambda x: -x[2])

    # Clip duration per QA (as in the paper's Fig. 3a), 5 s bins.
    durs = [r['clip_end'] - r['clip_start'] for r in qa]
    bins = collections.Counter(int(d // 5) for d in durs)
    hist = [[b * 5, bins.get(b, 0)] for b in range(0, max(bins) + 1)]

    spans = collections.Counter(min(len(r['evidence']), 5) for r in qa)
    out = dict(
        n_qa=len(qa), n_train=len(train), n_test=len(test),
        n_videos=len({r['video_path'] for r in qa}),
        n_tasks=len({r['task'] for r in qa}), n_domains=len(dom),
        mean_dur=round(sum(durs) / len(durs), 1),
        mean_spans=round(sum(len(r['evidence']) for r in qa) / len(qa), 2),
        domains=domains, reasoning=reasoning, sources=sources, hist=hist,
        spans=[[k, spans[k]] for k in sorted(spans)],
    )
    with open(os.path.join(PAGE, 'static/data/stats.js'), 'w') as f:
        f.write('// Generated by tools/make_stats.py from the released annotations.\n')
        f.write('window.PROC_STATS = ' + json.dumps(out, separators=(',', ':')) + ';\n')
    print({k: v for k, v in out.items() if not isinstance(v, list)})


if __name__ == '__main__':
    main()
