"""Parse the camera-ready (arXiv 2512.03479v2) result tables into static/data/results.js.

tools/paper/ holds verbatim copies of the arXiv v2 TeX sources the numbers come from.
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PAGE = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(HERE)


def strip_comments(tex):
    return '\n'.join(l for l in tex.splitlines() if not l.lstrip().startswith('%'))


def cell(c):
    """'\\cellcolor{bestgreen}51.4' -> (51.4, 'best')."""
    mark = 'best' if 'bestgreen' in c else 'second' if 'secondred' in c else None
    c = re.sub(r'\\cellcolor\{[^}]*\}', '', c).strip()
    if c in ('-', '--', ''):
        return None, mark
    return float(c), mark


def rows(body, ncols):
    """Yield (group, name, [values], [marks]) from a booktabs body."""
    group = None
    body = re.sub(r'\\noalign\{[^}]*\}|\\cdashline\{[^}]*\}\[[^]]*\]', '', body)
    for chunk in body.split('\\\\'):
        chunk = ' '.join(chunk.split())
        g = re.search(r'\\textcolor\{groupgray\}\{(.*)\}\}', chunk)
        if g:
            group = re.sub(r'\\textsc\{|\}', '', g.group(1)).strip()
            continue
        if '&' not in chunk or '\\midrule' in chunk and chunk.count('&') < 3:
            continue
        chunk = chunk.replace('\\midrule', '').replace('\\bottomrule', '').strip()
        parts = [p.strip() for p in chunk.split('&')]
        if len(parts) != ncols + 1:
            continue
        vals, marks = zip(*(cell(p) for p in parts[1:]))
        yield group, parts[0], list(vals), list(marks)


def main_table():
    tex = strip_comments(open(os.path.join(HERE, 'paper/procobject-10.tex')).read())
    body = tex.split('\\midrule', 1)[1].split('\\end{tabular}')[0]
    out = []
    for group, name, vals, marks in rows(body, 18):
        out.append(dict(group=group, model=name, v=vals, m=marks))
    return out


def rows_mh(body):
    group = None
    body = re.sub(r'\\noalign\{[^}]*\}|\\cdashline\{[^}]*\}\[[^]]*\]', '', body)
    for chunk in body.split('\\\\'):
        chunk = ' '.join(chunk.split())
        g = re.search(r'\\textcolor\{groupgray\}\{(.*)\}\}', chunk)
        if g:
            group = re.sub(r'\\textsc\{|\}', '', g.group(1)).strip()
            continue
        chunk = chunk.replace('\\bottomrule', '').strip()
        parts = [p.strip() for p in chunk.split('&')]
        if len(parts) != 8:
            continue
        vals, marks = zip(*(cell(p) for p in parts[2:]))
        yield dict(group=group, model=parts[0], input=parts[1], v=list(vals), m=list(marks))


if __name__ == '__main__':
    main = main_table()
    tex = strip_comments(open(os.path.join(HERE, 'paper/5_experiment.tex')).read())
    tabs = re.findall(r'\\begin\{tabular\}(.*?)\\end\{tabular\}', tex, re.S)
    ablation_free = [t for t in tabs if 'mIoP' in t or 'Test Seen' in t]
    multihop = list(rows_mh(ablation_free[0].split('\\midrule', 1)[1]))
    alfred = [dict(group=g, model=n, v=v, m=m)
              for g, n, v, m in rows(ablation_free[1].split('\\midrule', 1)[1], 4)]
    data = dict(main=main, multihop=multihop, alfred=alfred)
    for k, v in data.items():
        print(k, len(v))
        for r in v:
            print('  ', r.get('group'), '|', r['model'], r.get('input', ''), r['v'])
    with open(os.path.join(PAGE, 'static/data/results.js'), 'w') as f:
        f.write('// Generated by tools/parse_tables.py from the arXiv 2512.03479v2 TeX tables.\n')
        f.write('window.PROC_RESULTS = ' + json.dumps(data, separators=(',', ':')) + ';\n')
